### ISSUE TITLE
List (traverse / sequence) applicative or monadic

### ISSUE THREAD

**Issue by AlbertoDePena** [demystifyfp/FsToolkit.ErrorHandling#10]
I notice those are implemented using recursion. According to Scot Wlaschin, its more efficient (tail-recursion) to implement those functions using fold. 

See https://fsharpforfunandprofit.com/posts/elevated-world-4/#implementing-traverse-using-fold

**Comment by demystifyfp** [comment]
My initial implementation was using `foldBack` as mentioned in the blog post.  But I hit some roadblock in that implementation, and I am not able to recollect what it was.  

From that blog post,

![image](https://user-images.githubusercontent.com/30935826/53297007-e43e6b80-383c-11e9-841e-bacd9a875895.png)

The implementations here are all tail-recursive and hence it won't fail in the large lists.

**Comment by AlbertoDePena** [comment]
Awesome! Thanks for the clarification :)
