### ISSUE TITLE
Please add Yield() for OptionCE

### ISSUE THREAD

**Issue by AntyaDev** [demystifyfp/FsToolkit.ErrorHandling#101]

**Comment by TheAngryByrd** [comment]
Could you elaborate?

**Comment by AntyaDev** [comment]
Hi @TheAngryByrd 
Your implementation of option {} doesn't support yield operator
https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/OptionCE.fs

member this.Yield(x) =

**Comment by TheAngryByrd** [comment]
Ok but why would this need to be implemented? And how?

**Comment by AntyaDev** [comment]
Sorry, that didn't put a context.
If for example, I want to use 

option {
    for in do
        yield item // this will be a compile error 
}

I faced with this limitation recently and needed to switch from using CE.

**Comment by TheAngryByrd** [comment]
Option isn't for dealing with lists so I'm unsure if this is the computation expression you need in that scenario.
