### ISSUE TITLE
AsyncResult.mapAsync? (or some other name)

### ISSUE THREAD

**Issue by witoldsz** [demystifyfp/FsToolkit.ErrorHandling#103]
I am beginning my journey with F# and I am just figuring out there is so much missing in F# standard library. That is a surprise for me, and I am so glad I have found this library full of useful stuff.

I am trying to port some of the functions I use currently in my other projects, for example:

```fsharp
let map??? (fn: 'T -> Async<'T2>) (input: AsyncResult<'T, 'TError>) : AsyncResult<'T2, 'TError> =
  async {
    match! input with
    | Ok t -> return! fn t |> AsyncX.map Ok
    | Error e -> return Error e
  }

let mapErr??? (fn: 'TError -> Async<'TError2>) (input: AsyncResult<'T, 'TError>) : AsyncResult<'T, 'TError2> =
  async {
    match! input with
    | Ok t -> return Ok t
    | Error e -> return! fn e |> AsyncX.map Error
  }

// P.S. elsewhere:
module AsyncX =
  let bind f x = async.Bind(x, f) // f: 'a -> Async<'b> -> x: Async<'a> -> Async<'b>
  let map f = bind (f >> async.Return) // f: 'a -> Async<'b> -> Async<'a> -> Async<'b>
```

I don't know what would be the best name for this `map???`, maybe `mapAsync` (original name in TypeScript version was `mapP` where `P` stands for _Promise_)… Or maybe it's more of a `bind` that a `map` family? It is so often that when you try to insert the async function into your pipeline, that async function is pipeline's `Result<'a, 'b>` agnostic, it returns just `a -> Async<'b>` and with this `map???` I can easily insert it into the `AsyncResult<'a, 'b>` with no extra transformations.

What would you say?

**Comment by TheAngryByrd** [comment]
Yeah I struggle with what the correct terminology would be. I think it goes into `bind` territory since `bind` infers unwrapping a thing to operate on. So we would end up providing for AsyncResult a`bind` which takes a `'a -> Async<Result<'b,'c>>` and a `bindAsync` which takes a `'a -> Async<'b>` and any other `bindXYZ` for Tasks/Jobs/Promises and possible variants for the `Error` path as well but I tend to find needing to bind on the error path less and `map`s tend to cover most cases.

**Comment by TheAngryByrd** [comment]
Even though we don't provide all the functional `bindXYZ` variants we do provide overloads for them in our computation expressions, which many people like using since it tends to read nicer.

**Comment by witoldsz** [comment]
OK, thanks. I am still wrapping my head around composing functions (`>>` and `|>`) and using computation expressions (this is new, have not seen anything like this, expect for Haskell `do`) and I can always just add these methods as they are easy to write (at least for me now) and most other things are implemented in this superb _FsToolkit_ already (it reminds me of [jOOλ - The Missing Parts in Java 8](https://github.com/jOOQ/jOOL) _jOOλ improves the JDK libraries in areas where the Expert Group's focus was elsewhere_.)

**Comment by TheAngryByrd** [comment]
Thanks :) 

I think this is answered so going to close.
