### ISSUE TITLE
Add Warnings for ValidationCE

### ISSUE THREAD

**Issue by Swoorup** [demystifyfp/FsToolkit.ErrorHandling#104]
It would be nice to be on par with Chessie, which also has warnings support, which are not necessarily errors.

**Comment by TheAngryByrd** [comment]
I think we would want to encode that into a new DU type with `Ok | Warn | Error` but that might be outside the scope of this library since we're only dealing with the `FSharp.Core Result` type. I know Chessie does it with `Ok of 'a * 'Msg list | Error of 'Msg list` but I don't really like how that's done.

**Comment by Swoorup** [comment]
Would have thought Ok would contain `('value * 'warning list * 'info list)` and Error just `'error list`?

**Comment by TheAngryByrd** [comment]
You _can_ do that but I don't like it since you're not using the type system to your advantage. 

I'd say come up with a version that works and submit a PR so we can discuss the implementation if you find that pattern useful.

**Comment by Swoorup** [comment]
The reasoning for not choosing a DU is that, warnings/info are not necessary a failure or should cause the system to fail, only errors would. i.e I would want to be able to get the Ok value, and simply log out or gather the warnings or infos and pipe it elsewhere? Whereas error would cause a fail?

```
type Validation<'successValue, 'err, 'warn>  = 
	| Ok of 'successValue * 'warn list
    | Error of 'err
```

**Comment by AlexeyRaga** [comment]
I think that having warnings etc. should be somehow outside of the library concern. Like, what if I also want `Info` or `Critical` etc?.

One can always come up with their own way of tagging en error and just use it:

```
type Severity<'a> =
    | Critical of 'a
    | Warning of 'a
    
    
let (xxx : Validation<MySuccess, Severity<MyError>>) = ....
```

**Comment by TheAngryByrd** [comment]
Yeah since I haven't seen a PR for this and you could always build/layer your needs on top of this library I'm going to close this.
