### ISSUE TITLE
Forking logic using Result.Error

### ISSUE THREAD

**Issue by no1melman** [demystifyfp/FsToolkit.ErrorHandling#119]
So i've got this logic:

```
  cacheGet
    | Success -> return data
    | Failure ->
        apiGet
        |> cacheSet
```
So if `cacheGet` is successful, then we just return the data.
If `cacheGet` fails, then we just go straight to the API, once the data comes back, if that is successful, cache it, otherwise filter the data through....

Obviouly this is a little trickier because everything is basically a return function (`'a -> Task<Result<'b'c>>`) and we're replacing the error branch with further successes....

I don't know if this problem is resonating with anyone, but to solve, I've created

```fsharp
module TaskResult =
   // inspired by the Result.valueOf
  let bindValueOr f res = // ('a -> Task<Result<'b,'c>>) -> Result<'b,'a> -> Task<Result<'b, 'c>>
    match res with
    | Ok x -> Task.singleton (Ok x)
    | Error x -> f x

  let bindTRValueOr f taskResult = // ('a -> Task<Result<'b,'c>>) -> Task<Result<'b,'a>> -> Task<Result<'b,'c>>
    taskResult |> Task.bind (bindValueOr f)
```

and usage:

```fsharp
  let apiGet = // () -> Task<Result<'a,'b>>
  let apiGetThenCache = // Task<Result<'a,'c>>
    apiGet()
        |> TaskResult.bind (fun (a, b) -> 
            Caching.cacheData b  |> Task.map (fun _ -> Ok a) // I want to store b, but return a, a is the deserialised form
          )

  Caching.hasCachedData
  |> Task.bindTRValueOr apiGetThenCache
```

I don't know if this is sparking anyone's thoughts - or if I've completely misused the suite of functions.... if there is a simpler way with existing 

If there isn't - what would be the appropriate way/hunger to incorporate this into the current library?

**Comment by TheAngryByrd** [comment]
Sorry for the late response:

I think the term we'd want to go with is `orElse` which I think is used in the [Option.OrElse](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html#orElse) module.
