### ISSUE TITLE
Add  requireEqualTo and requireEqual and deprecate requireEquals in favor of requireEqual

### ISSUE THREAD

**Issue by cmeeren** [demystifyfp/FsToolkit.ErrorHandling#13]
Creating a separate issue for this so it doesn't get lost. Previously mentioned in https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/3#issuecomment-461419881

**Comment by demystifyfp** [comment]
Thanks, @cmeeren for doing this.

**Comment by demystifyfp** [comment]
Fixed in 1.0.0. The `requireEquals` has been removed instead of marking it as deprecated.
