### ISSUE TITLE
Common Pattern Result -> Option

### ISSUE THREAD

**Issue by joshpme** [demystifyfp/FsToolkit.ErrorHandling#137]
In many of our companies projects, we see this pattern. Where we need treat a result as an option. 

The code normally looks something like this:
```
  module Option =
    let ofResult =
      function
      | Ok v -> Some v
      | Error _ -> None
```
Is this something worth adding to this project? (or are we doing it wrong)

**Comment by TheAngryByrd** [comment]
Absolutely! Please send a PR.

**Comment by njlr** [comment]
https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/147
