### ISSUE TITLE
Simplify namespace structure

### ISSUE THREAD

**Issue by cmeeren** [demystifyfp/FsToolkit.ErrorHandling#14]
While testing in https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/12#issuecomment-480487306, I noticed that I had to open separate namespaces to get the `result` and `asyncResult` instances, and yet another one (the main `FsToolkit.ErrorHandling`) to get the helpers (`Result.xxx` etc.).

I suggest that we make `result` and `asyncResult` available in the main namespace (perhaps other CEs too?). While I may be biased to my own usage, I guess that people using this library are very likely to want these builders, so we shouldn't require them to have three `open`s in every relevant file.

(I haven't investigated the rest of the namespace/module structure of FsToolkit.ErrorHandling; there might be other places we could simplify, too.)

**Comment by demystifyfp** [comment]
I agree. Will incorporate it in the new release.

**Comment by demystifyfp** [comment]
Fixed in 1.0.0
