### ISSUE TITLE
use [<Struct>] for computation builders

### ISSUE THREAD

**Issue by AntyaDev** [demystifyfp/FsToolkit.ErrorHandling#15]
Does it make sense to use [< struct >] for computation expression builders?

```fsharp
[<Struct>]
type AsyncResultBuilder()
```

**Comment by cmeeren** [comment]
AFAIK no, because there's only ever one instance used (normally). It's that instance you're referring to when you write e.g. `result { }`. So there's never any allocation of the builder when the CE is used.

**Comment by demystifyfp** [comment]
I agree with @cmeeren. The `Struct` attribute meant for value types (record types that model data). Here the `AsyncResultBuilder` is a type that model behaviour.

**Comment by demystifyfp** [comment]
@AntyaDev Can I close this one?
