### ISSUE TITLE
Seq.sequenceResultM returns a list instead of a seq

### ISSUE THREAD

**Issue by dnperfors** [demystifyfp/FsToolkit.ErrorHandling#158]
**Describe the bug**
When using `Seq.sequenceResultM` the result will is a `'t list`, this is not what I would have expected from a `Seq` function. 

**To Reproduce**
```
seq { "1"; "2"; "3" }
|> Seq.map tryParseInt
|> Seq.sequenceResultM

// Actual:
// OK [ 1; 2; 3 ]
// Expected:
// OK seq { 1; 2; 3 } 
```

**Expected behavior**
I expect that functions in the `Seq` modules will return a `Seq`, unless I specifically tell otherwise.

(I know a `list` is also a `seq`, but still...)

**Comment by TheAngryByrd** [comment]
Agreed, I didn't realize this was the case!
