### ISSUE TITLE
Add missing Tests from Cvdm.ErrorHandling

### ISSUE THREAD

**Issue by demystifyfp** [demystifyfp/FsToolkit.ErrorHandling#16]

**Comment by TheAngryByrd** [comment]
Are there any additional tests we should add? cc @cmeeren

**Comment by cmeeren** [comment]
No idea. It's been so long, and the tests in FsToolkit.ErrorHandling seems to be written/structured/refactored differently (using Expecto) than when we did the merge, so I have no idea what tests are currently in FsToolkit.ErrorHandling. My best suggestion would be that you simply investigate [the tests](https://github.com/cmeeren/Cvdm.ErrorHandling/tree/master/src/Cvdm.ErrorHandling.Tests) and see if the behaviour they test are covered by your tests.

I'm mostly concerned about the CE tests (Result and AsyncResult); the helpers are more of an "it compiles, it works" variant.

**Comment by TheAngryByrd** [comment]
Ok until we have something more actionable, i'm gonna close this.
