### ISSUE TITLE
TaskResult.ofTask?

### ISSUE THREAD

**Issue by njlr** [demystifyfp/FsToolkit.ErrorHandling#161]
Is there a function to catch a `Task` and turn it into a `TaskResult`? 

Something like this:

```fsharp

module TaskResult = 

  let ofTask (t : Task<'a>) = 
    task {
      try
        let! x = t

        return Ok t
      with exn ->
        return Error exn
    }
```

I'm not sure how well this would work given that tasks are "hot".

**Comment by TheAngryByrd** [comment]
Not a direct function but you could use 

```fsharp
myTask
|> Task.catch
|> Task.map Result.ofChoice
```

**Comment by TheAngryByrd** [comment]
That being said, I'd recommend using a `taskResult` CE with a try/with as I don't want to implement every possible little conversion in function form. 

1. Naming is hard and setting expectations of what a function does is even harder.  There's already and "TaskResult.ofTask` but it doesn't do a catch. Should it? It's hard to know what every expects each function to do.
2. [This README](https://github.com/demystifyfp/FsToolkit.ErrorHandling/tree/master/tools/FunctionMap#table) shows the ever growing giant list of functions that are across the different libraries already. 
3. [Computation expressions have a Source overload](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/83) which cuts down on maintaining every little tiny conversion.
