### ISSUE TITLE
Making TaskResult and JobResult libraries

### ISSUE THREAD

**Issue by TheAngryByrd** [demystifyfp/FsToolkit.ErrorHandling#17]
It was requested [via twitter](https://twitter.com/sergey_tihon/status/1116247497234628613) to have a `TaskResult` added to this library.  I do believe this would be a good idea, as I also work with task heavy CE workloads and rely on the Result type.  

As mentioned in that tweet thread, since the main library wants to be Fable compatible, it would have to be its own separate library. `FsToolkit.ErrorHandling.Tasks` (something something naming is hard).

In addition to this, I use Hopac quite a bit and have authored the `Chessie.Hopac`. Similar to the above, it would be its own library `FsToolkit.ErrorHandling.Hopac`.  

I'd be willing to implement both of these libraries if this proposal makes sense.

**Comment by demystifyfp** [comment]
It makes sense to have them as separate libraries and keep this one only depends on FSharp.Core. 

How do you want to go about it? Can we have it as a mono-repo here with the build script publishing three different packages or separate repositories in your GitHub account? I am fine with whatever works for you.

**Comment by cmeeren** [comment]
Agree that separate libraries should be used here.

Since `Task` is hot (as opposed to `Async` being cold), are there any composability concerns relevant here? I think I remember someone claiming in a blog post or some such that `Task` being hot makes it less composable than `Async`, though I can't immediately see exactly how (provided similar combinators for `Task` as for `Async`).

**Comment by TheAngryByrd** [comment]
@demystifyfp  I think keeping it in this repository makes sense.  Easier for the dependent libraries to adjust to changes.

@cmeeren Yeah 99% of `Task`s are started or "hot" by the time you get a reference to them, so yes they are less composable. Also there's other downsides like [they're not tail call optimized](https://github.com/rspeele/TaskBuilder.fs#tail-calls-are-not-optimized). The main benefit of using `Task` over `Async` is the [speed bonus](https://github.com/giraffe-fsharp/Giraffe/issues/53).  However it may remain to be seen if having `taskResult` keeps speed up.  I would probably need to make a benchmark for that as well.

**Comment by cmeeren** [comment]
> so yes they are less composable

But why/how, in concrete terms? And are there any concerns of relevance to usage of a `taskResult` CE?

**Comment by TheAngryByrd** [comment]
Well some people's definition of composable implies laziness/cold so you're dealing with slightly different semantics about how your `FuturesObject` will behave.  But really it's not less "composable" in the strict sense of the word.

**Comment by demystifyfp** [comment]
Thanks, @TheAngryByrd for initiating this. Feel free to let me know If there is any help required.

**Comment by demystifyfp** [comment]
@TheAngryByrd Have you seen this https://github.com/crowded/ply ?

**Comment by TheAngryByrd** [comment]
Yes it's pretty awesome work. Not sure if I'll use it quite yet.

**Comment by cmeeren** [comment]
Would be quite a lot of builders! taskResult, taskResultOption, vtaskResult, etc...
