### ISSUE TITLE
TaskResultCE breaks with an if

### ISSUE THREAD

**Issue by kerams** [demystifyfp/FsToolkit.ErrorHandling#176]
**Describe the bug**

With 3.0.0-beta006, the following code does not compile. The problem is on `return 55` and the compiler complains the expected type is `unit`, not `int`.

```fsharp
let taskRes call maybeCall = taskResult {
    if true then
        do! call (): Task

    let! (res: string) = maybeCall (): Task<Result<string, unit>>
    return 55 }
```

If you remove the `if`, everything works.

**Expected behavior**
Compiles and the type of `taskRes` is `Task<Result<int, unit>>`.

**Comment by TheAngryByrd** [comment]
Yeah this definitely is a bug.

---

For a workaround for now:

```fsharp
if true then
  let! _ = call ()
  ()
```

**Comment by kerams** [comment]
That's no good, it needs to execute when the condition passes :).

I can do this, however:

```fsharp
let taskRes call maybeCall = taskResult {
    do! task {
        if true then
            do! call (): Task
    }

    let! (res: string) = maybeCall (): Task<Result<string, unit>>
    return 55 }
```

**Comment by TheAngryByrd** [comment]
I'll have a fix out here shortly.  Thank you for testing this beta 🙏
