### ISSUE TITLE
List.traverseResultA and friends have x @ y on the error branch, this could potentially blow up

### ISSUE THREAD

**Issue by abelbraaksma** [demystifyfp/FsToolkit.ErrorHandling#178]
**Describe the bug**
The [`List.traverseResultA` function](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/929208c7cbd0cb25234f8539e98c4ae6dda08a28/src/FsToolkit.ErrorHandling/List.fs#L48) and similar ones have this critical path:

```f#
            match state, fR with
            | Ok ys, Ok y -> traverseResultA' (Ok(y :: ys)) f xs
            | Error errs, Error e -> traverseResultA' (Error(errs @ e)) f xs
            | Ok _, Error e
            | Error e, Ok _ -> traverseResultA' (Error e) f xs
```

Namely: `Error(errs @ e)`.

If you have many errors (in my situation is was importing an Excel file and all cells in a column were bad), the performance is exponential.

To solve this, one way would be a simple fix to just `e :: errs` the errors and do a `List.rev` at the end.

**Comment by TheAngryByrd** [comment]
Ouch, yeah that's bad. I mentioned the error path needs to be considered as well in https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/167 when doing a performance pass at it.

**Comment by TheAngryByrd** [comment]
I looked into this briefly and `errs @ e` are two lists so your recommended fix wouldn't work exactly.  So I think this would be better changed to be some type of while loop semantics to get performance.

**Comment by abelbraaksma** [comment]
Oh, yeah, you're right. Though, arguably, the new lists will be shorter than the tally, so a quick `rec` with `e::errs` would be nice. But that would, perhaps, invert the order of errors? Hmm, tricky.

You could maintain `State` in a `ResizeArray`, and on `return` you'd convert that to a `list`? Not ideal either.

**Comment by TheAngryByrd** [comment]
I did benchmark this a bit ago: https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/167], various tradeoffs

Yeah idk why it's currently implemented with the `@` after looking at it now.

**Comment by abelbraaksma** [comment]
Change looks good, thanks!
