### ISSUE TITLE
Documentation for Validation operators mentions Bind (>>=), but the library doesn't implement it

### ISSUE THREAD

**Issue by sonicbhoc** [demystifyfp/FsToolkit.ErrorHandling#188]
**Describe the bug**
Looking through the source code through for the validation operators, the Bind operator (`>>=`) is not defined, even though the documentation references it specifically.

Instead, the following error message is displayed:

    FS0043: Expecting a type supporting the operator `>>=` but given a function type. You may be missing an argument to a function.

**To Reproduce**
Attempt to use the `>>=` operator

**Expected behavior**
Function composition with Bind

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Browser: Microsoft Edge 106
 - Version: 3.1.0

**Comment by TheAngryByrd** [comment]
Yeah looks like the validation operators aren’t opening the Result ones. Will be happy to take a PR for this.
