### ISSUE TITLE
FSharp.Core version warning (net7.0)

### ISSUE THREAD

**Issue by quentez** [demystifyfp/FsToolkit.ErrorHandling#194]
**Describe the bug**
Following what I suspect to be [this change](https://github.com/demystifyfp/FsToolkit.ErrorHandling/commit/ca41c0d37212c1399d0ef46c1309ab41f4aef4e7#diff-377fe73bf860b37e7d9a8ca5be27762668b3a08aac581b435d4c31b737d905cdL5), I now get the following warning after upgrading to version `3.3.0`:

```
[NU1608] Detected package version outside of dependency constraint: FsToolkit.ErrorHandling 3.3.0 requires FSharp.Core (= 4.7.2) but version FSharp.Core 7.0.0 was resolved.
```

**To Reproduce**
1. Add `FsToolkit.ErrorHandling.TaskResult` version `3.3.0` to a `net7.0` project.
2. Build the project.

**Expected behavior**
No warning.

**Desktop:**
 - OS: macOS 13.0

**Comment by Dzoukr** [comment]
Yup, I think there should be `>=` instead of `=`

<img width="138" alt="image" src="https://user-images.githubusercontent.com/851307/200791435-a1088e6f-6807-4193-8eee-9308a0d5052a.png">

**Comment by cmeeren** [comment]
Yes, this was `>=` before, but is now `=`. For us who have enabled warnings as errors, this precludes updating FsToolkit.ErrorHandling.

**Comment by TheAngryByrd** [comment]
Ah paket has changed rules around its version. Lemme see if I can clean it up

**Comment by TheAngryByrd** [comment]
Opened an issue on paket as it seems they are generating a nuspec file differently https://github.com/fsprojects/Paket/issues/4183

**Comment by TheAngryByrd** [comment]
I think i'm gonna pull the version from nuget for the moment

**Comment by yreynhout** [comment]
This happens for `net6.0` projects too.

**Comment by abelbraaksma** [comment]
Fwiw, 3.2.0 dies not exhibit this problem, it has the versions as `>=`. And if I saw it correctly, 3.3 is beta, or did you pull the definitive version already @TheAngryByrd.

**Comment by cmeeren** [comment]
Do you mean that it won't be fixed before upstream fixes it? Since the NuGet package is now locked to a fairly old F# version, it may prevent many people from updating until it's fixed.

**Comment by TheAngryByrd** [comment]
> Do you mean that a new package with unlocked FSharp.Core version won't be published before upstream fixes it?

Yes, I'm not gonna get into the habit of hand editing nuget packages everytime I need to do deploy and this helps the ecosystem.

**Comment by TheAngryByrd** [comment]
Just published https://www.nuget.org/packages/FsToolkit.ErrorHandling/3.3.1-beta002#dependencies-body-tab

can you give it a try?

**Comment by quentez** [comment]
Looking good on my end!

**Comment by cmeeren** [comment]
Looks good on NuGet!

<img width="560" alt="image" src="https://user-images.githubusercontent.com/7766733/202851958-900a26dd-5861-49a4-9b09-4e8788c35964.png">

**Comment by abelbraaksma** [comment]
Question: do we really need to force upgrade to F# Core 7.0? On NetStandard 2.1, the lowest denominator should probably be used, which is 6.0.2, or 6.0.5.

/cc @TheAngryByrd
