### ISSUE TITLE
Add Option.ofPair

### ISSUE THREAD

**Issue by AlbertoDePena** [demystifyfp/FsToolkit.ErrorHandling#207]
**Is your feature request related to a problem? Please describe.**

Not a problem, just a feature request

**Describe the solution you'd like**

Utility method to convert 

```F#
static member TryParse:
   s     : string *
   result: byref<int>
        -> bool
```
to Option

```F#
[<RequireQualifiedAccess>]
module Option =

    let ofPair (x: bool * 'a) =
        match x with
        | true, y -> Some y
        | false, _ -> None

let toInt32 (value: string) = 
    Int32.TryParse value 
    |> Option.ofPair

"HI" |> toInt32 // None
"10" |> toInt32 // Some 10
```

**Describe alternatives you've considered**

```F#
let tryParseInt (value: string) =
    let (parsed, parsedValue) = Int32.TryParse value
    if parsed then
        Some parsedValue
    else
        None
```

**Additional context**

Please ignore if this already exists. If so, where can I find such utility method?

**Comment by TheAngryByrd** [comment]
There isn't an `ofPair` but there is a [tryParse](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/Option.fs#L40) with [examples](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/aa87d3de3f9977f399bd13749d32afbfc96ada54/tests/FsToolkit.ErrorHandling.Tests/Option.fs#L32).  That being said, this only accounts for that exact `TryParse` signature and doesn't work for Fable.  

Definitely willing to take a PR for this. Also would be good addition to `ValueOption` set of functions as well.

**Comment by AlbertoDePena** [comment]
@TheAngryByrd you mean the SRTP is not Fable compliant correct? I wouldn't mind taking a stab at the PR

**Comment by TheAngryByrd** [comment]
Yeah I remember it having issues with fable. I haven’t tried with the 4.0 versions though. 

Great. Please ask questions if you have them!

**Comment by njlr** [comment]
Was curious if this works now. It compiles but the behaviour is incorrect: https://github.com/fable-compiler/Fable/issues/3332

**Comment by AlbertoDePena** [comment]
@njlr

I think adding `Option.ofPair` (the name does not matter) is nice since not everyone (including me) is super comfortable with SRTP =)
