### ISSUE TITLE
Add sequenceResultA and friends to Array

### ISSUE THREAD

**Issue by boggye** [demystifyfp/FsToolkit.ErrorHandling#278]
Could you please make the methods present in List: https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/List.fs  available for Array as well?

It is a bit of a pain to convert between types, especially when I need to use arrays to process lots of data (forced by external api) and I need to squeeze as much performance as possible.

Thank you

**Comment by TheAngryByrd** [comment]
Happy to accept a PR for this 😄

**Comment by boggye** [comment]
The problem is that the code is a bit above my F# expertise, but I will try ...
