### ISSUE TITLE
AsyncValidationCE use! seems to close the stream prematurely

### ISSUE THREAD

**Issue by atlemann** [demystifyfp/FsToolkit.ErrorHandling#282]
**Describe the bug**

`use!` in AsyncValidation CE closes files prematurely

**To Reproduce**

Use this code snippet and try to read a file from disk:

```fsharp
open FsToolkit.ErrorHandling

let readFile (file: FileInfo) =
    asyncValidation {
        use! stream = AsyncValidation.retn (file.OpenRead())
        use reader = new StreamReader(stream)
        let text = reader.ReadToEnd()
        return text
    }
```

**Expected behavior**
Getting the text of the file

**Actual behavior**
```
System.ObjectDisposedException : Cannot access a closed file.
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
```

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by TheAngryByrd** [comment]
What version are you using? https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/271 fixed issues around this an [4.15.3](https://github.com/demystifyfp/FsToolkit.ErrorHandling/releases/tag/4.15.3).

**Comment by atlemann** [comment]
`4.15.1`, ok my bad. I'll try to update and try again.

**Comment by atlemann** [comment]
Bumped to 4.18.0 and it fixes it. And some other issues I've had with let! of asyncResult in asyncValidation CE. Sorry for wasting your time and thanks for a great library!
