### ISSUE TITLE
Add Result.sequenceAsync

### ISSUE THREAD

**Issue by cmeeren** [demystifyfp/FsToolkit.ErrorHandling#48]
I propose adding `Result.sequenceAsync` (or is it `Async.sequenceResult`? I think it's the former). An example implementation is:

```f#
let sequenceAsync (resAsnc: Result<Async<'a>, 'b>) : Async<Result<'a, 'b>> =
    async {
      match resAsnc with
      | Ok asnc ->
          let! x = asnc
          return Ok x
      | Error err -> return Error err
    }
```

I have had a need for this when using the `Result.apply` or `Result.map` operators (or the corresponding `Validation` operators, which I am using) with an `Async`-returning function. For example, I have the following code:

```f#
let! webhook =
  Workflows.createWebhook  // createWebhook is async
  <!> parseRequiredAttr a.callbackUrl WebhookCallbackUrl.TryCreate
  <*> parseOptOptAttr a.authorizationHeader WebhookAuthorizationHeader.TryCreate
  |> Result.sequenceAsync
```

The implementation details aren't important. The core concept is that I have an async function `createWebhook` that I apply to `Result`-wrapped arguments using `<!>` and `<*>`. Without `Result.sequenceAsync`, I end up with `Result<Async<Webhook, Error>>` whereas I'd like `Async<Result<Webhook, Error>>`.

This is a situation users will end up with every time they have an `Async`-returning function that they use with the `apply`/`map` operators. It seems general/common/simple enough that it's worth adding to the library.

**Comment by TheAngryByrd** [comment]
Usually when I end up with that situation I haven't done something right. The functions all need to align to the expected output type which is `Async<Result<Webhook, Error>>`.

So for instance I would create some helpers do:

```fsharp
//looks like were missing some of these helper functions like AsyncResult.ofAsync or AsyncResult.ofResult
module AsyncResult=
  let ofAsync (a : Async<_>) = a |> Async.map Result.Ok
  let ofResult (r : Result<_,_>) = r |> Async.singleton

let createWebhook = Workflows.createWebhook  |> AsyncResult.ofAsync
let parseRequiredAttr x y = parseRequiredAttr x y |> AsyncResult.ofResult
let parseOptOptAttr x y = parseOptOptAttr x y |> AsyncResult.ofResult
```

Then in the implementation use the AsyncResult operators to do:

```fsharp
let! webhook =
  createWebhook
  <!> parseRequiredAttr a.callbackUrl WebhookCallbackUrl.TryCreate
  <*> parseOptOptAttr a.authorizationHeader WebhookAuthorizationHeader.TryCreate
```

The reason I'm _loosely_ against this is because I've seen people just trying to make types fit without actually understanding what is going on.  That said I could be totally wrong about this.

**Comment by cmeeren** [comment]
The operators I'm using are the `Validation` operators, and they are only available for `Result`.

Besides, is there a significant conceptual difference between using wrappers to make all the types match up up front (or as you go along and call them), versus transforming at the end?

**Comment by TheAngryByrd** [comment]
> The operators I'm using are the Validation operators, and they are only available for Result.

Looks like we should also add those for Async/Task/JobResult variants too :)

> The latter seems to be less work/verbose.

Yeah, that is definitely a downside to the alternative I have given.

**Comment by cmeeren** [comment]
> Looks like we should also add those for Async/Task/JobResult variants too :)

Would be great! In my specific case, I'd still want `Result.sequenceAsync` though, both due to being less boilerplate, and because it's confusing to have to switch back and forth between different operators.

**Comment by TheAngryByrd** [comment]
Make a PR :)

**Comment by tamizhvendan** [comment]
@cmeeren The latest version `1.2.2` has your changes. Can you verify and close this issue?

**Comment by cmeeren** [comment]
It's there, thanks! 👍
