### ISSUE TITLE
Add documentation for JobResult

### ISSUE THREAD

**Issue by tamizhvendan** [demystifyfp/FsToolkit.ErrorHandling#52]
@TheAngryByrd I just noticed that we don't have the documentation for the JobResult library. We need to add it when we find the time!

**Comment by TheAngryByrd** [comment]
https://github.com/demystifyfp/FsToolkit.ErrorHandling/tree/master/gitbook/jobResult 

Is this not sufficient?

**Comment by tamizhvendan** [comment]
Oops, I didn't see that. We need to add that in the SUMMARY.md to show up. Added it just now!
