### ISSUE TITLE
Consider adding ignore method to each type

### ISSUE THREAD

**Issue by CameronAavik** [demystifyfp/FsToolkit.ErrorHandling#57]
I've found myself reaching many times for something like `AsyncResult.ignore` or `AsyncResultOption.ignore` to do the same thing that [`Async.Ignore`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/async.ignore%5B't%5D-method-%5Bfsharp%5D) does.

I've just been replacing it with `AsyncResult.map (fun _ -> ())` in my code, but I thought it might be a useful addition to the library for when you want to use the `do!` syntax on a function and you don't care about the response.

**Comment by cmeeren** [comment]
Side note: Instead of `AsyncResult.map (fun _ -> ())` you can do `AsyncResult.map ignore`.

**Comment by demystifyfp** [comment]
Thanks, @CameronAavik for the suggestion. Yes, It'd be useful. Are you planning to send any pull request?

**Comment by CameronAavik** [comment]
Yes, I'll make a PR later tonight for it.

**Comment by CameronAavik** [comment]
Finished in #58
