### ISSUE TITLE
Code on website renders incorrectly

### ISSUE THREAD

**Issue by cmeeren** [demystifyfp/FsToolkit.ErrorHandling#61]
For example https://demystifyfp.gitbook.io/fstoolkit-errorhandling/result/map2

Notice how every `'` is interpreted as a start/end string delimiter, causing incorrect colors.

![image](https://user-images.githubusercontent.com/7766733/68501373-45d52780-025e-11ea-9068-d792a7cd80a3.png)

**Comment by 64J0** [comment]
This issue should be closed since this bug is not happening anymore:

![image](https://user-images.githubusercontent.com/50725287/144660562-1247ba79-23ed-4f4c-a92c-f38551b4357e.png)
