### ISSUE TITLE
Add Option/Maybe CE

### ISSUE THREAD

**Issue by Swoorup** [demystifyfp/FsToolkit.ErrorHandling#65]
Doesn't it make sense to also add Option computation expression to this library?

**Comment by cmeeren** [comment]
I would certainly welcome that! I often define a very simple (`Return`/`ReturnFrom`/`Bind`) option CE in most of my projects where I also use FsToolkit.ErrorHandling, so I would certainly use it if it was implemented.

**Comment by TheAngryByrd** [comment]
Agreed. I think having an option CE is a good idea.
