### ISSUE TITLE
AsyncResult.ofTask does not work when using Task (not Task<T>)

### ISSUE THREAD

**Issue by AlbertoDePena** [demystifyfp/FsToolkit.ErrorHandling#7]

**Comment by cmeeren** [comment]
The `asyncResult` CE from Cvdm.ErrorHandling that [will be merged soon](https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/3#issuecomment-457924211) contains `Task` and `Task<_>` overloads for `Bind`, so I think `ofTask` will be superfluous then.

**Comment by demystifyfp** [comment]
Thanks, @cmeeren for jumping in. Last two months were just crazy, will get it done at the earliest I can.

**Comment by demystifyfp** [comment]
Fixed in 1.0.0. The new function `AsyncResult.ofTaskAction` will take care of this.
