### ISSUE TITLE
TaskOption

### ISSUE THREAD

**Issue by Micha-kun** [demystifyfp/FsToolkit.ErrorHandling#77]
Seeing there are methods for AsyncOption, TaskResult, and even TaskResultOption, I'm surprised that there isn't a module with functions for TaskOption. Even there is a computation expression, but no module functions. Exists any reason for that?

**Comment by TheAngryByrd** [comment]
Mostly an oversight.  I'm definitely for having more module level functions.

Seems like we dont have `AsyncOption` either. So we'd want to have module functions for:

- [ ] AsyncOption
- [ ] TaskOption
- [ ] JobOption

I'm not which all functions we should have but probably some basics like `map/bind/return` makes sense as a starting point.
