### ISSUE TITLE
Add AsyncResult.ofTask with non-generic Task passed in

### ISSUE THREAD

**Issue by ysangkok** [demystifyfp/FsToolkit.ErrorHandling#79]
Methods like [ConnectAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.connectasync?view=netcore-3.1#System_Net_Sockets_TcpClient_ConnectAsync_System_Net_IPAddress_System_Int32_) returns a non-generic Task, which cannot be used with AsyncResult.ofTask

**Comment by TheAngryByrd** [comment]
Sounds like a good addition!

**Comment by TheAngryByrd** [comment]
We have a function for that [ofTaskAction ](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/AsyncResult.fs#L32).

**Comment by ysangkok** [comment]
I tried that, this is the error I get:

```
Lightning.fs(237,94): 
error FS0001: The type 'unit' is not compatible with the type 'Task' [Backend.fsproj]
  
Lightning.fs(237,13): 
error FS0041: A unique overload for method 'Bind' could not be determined based on type information prior to this program point. A type annotation may be needed. 
Candidates: 
member AsyncResultBuilder.Bind : async':Async<'T> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>>, 
member AsyncResultBuilder.Bind : asyncResult:Async<Result<'T,'TError>> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>>, 
member AsyncResultBuilder.Bind : result:Choice<'T,'TError> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>>, 
member AsyncResultBuilder.Bind : result:Result<'T,'TError> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>>, 
member AsyncResultBuilder.Bind : task:Task * binder:(unit -> Async<Result<'T,'TError>>) -> Async<Result<'T,'TError>>, member AsyncResultBuilder.Bind : task:Task<'T> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>>, 
member AsyncResultBuilder.Bind : taskResult:Task<Result<'T,'TError>> * binder:('T -> Async<Result<'U,'TError>>) -> Async<Result<'U,'TError>> [Backend.fsproj]
```

**Comment by ysangkok** [comment]
let me prepare a complete example...

**Comment by ysangkok** [comment]
Actually, I get that error even with this:

```
namespace Lightning

open FsToolkit.ErrorHandling
module Lightning =

    let Test () =
        asyncResult {
            do! async { return (Ok "test") }
            return ()
        }
```

Is this not compatible with F# 4.5?

**Comment by TheAngryByrd** [comment]
Hmm we have a test that does bind against a unit task.

https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/e9e05ba10d7e770b52497545d659973c221c8235/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs#L148-L154


> Is this not compatible with F# 4.5?

Version [1.2.6](https://www.nuget.org/packages/FsToolkit.ErrorHandling/1.2.6) requires FSharp 4.6.2.

**Comment by TheAngryByrd** [comment]
It doesn't look like there's a good reason to not drop the minimum required FSharp.Core version, I'll open a PR for that.

**Comment by TheAngryByrd** [comment]
```
namespace Lightning

open FsToolkit.ErrorHandling
module Lightning =

    let Test () =
        asyncResult {
            do! async { return (Ok "test") }
            return ()
        }
```

`do!` is invalid here since you're trying to bind against something that has data.  In your case the value `"Test"`.  You have two options.

Ignore the result:

```fsharp
 let! _ = async { return Ok "test" }
```
or have the value be a unit:

```fsharp
do! async { return Ok () }
```

**Comment by ysangkok** [comment]
Aaaah, thank you so much! It makes sense, I get it. Indeed I would appreciate if the min version was F# 4.5, since that is what the Mono packages for Ubuntu ships.
