### ISSUE TITLE
Duplicate code?

### ISSUE THREAD

**Issue by AlbertoDePena** [demystifyfp/FsToolkit.ErrorHandling#8]
I see that we have the operators in AsyncResultOp.fs file and also at the bottom of the AsyncResult.fs file... Is there a reason for that?

**Comment by demystifyfp** [comment]
Thanks, @AlbertoDePena for spotting this. 
In the initial codebase, I had it in the `AsyncResult.fs` file and later refactored it to a separate namespace. While doing forget to remove this!

It will be removed in the `1.0.0` version.

**Comment by demystifyfp** [comment]
Fixed in 1.0.0
