### ISSUE TITLE
Validation (Result.tryCreate)

### ISSUE THREAD

**Issue by AlbertoDePena** [demystifyfp/FsToolkit.ErrorHandling#9]
Would it be possible to have a statically resolved parameter for a function instead of a type with a member? 

Lets say I wanted to have utility function to try create something...

Instead of:
```F#
type Longitude = private Longitude of double with
  member this.Value =
    let (Longitude lng) = this
    lng

  // double -> Result<Longitude, string>
  static member TryCreate (lng : double) =
    if lng > -90. && lng < 90. then
      Ok (Longitude lng)
    else
      sprintf "%A is a invalid longitude value" lng |> Error
```
something like this:
```F#
type Longitude = private Longitude of double

module Longitude =

  let value (Longitude x) = x

  // this could be named create / tryCreate / createResult
  let tryCreate (lng : dobule) =
     if lng > -90. && lng < 90. then
      Ok (Longitude lng)
    else
      sprintf "%A is a invalid longitude value" lng |> Error
```
That way my validation would be something like this:
```F#
open FsToolkit.ErrorHandling.Operator.Validation 

// CreatePostRequestDto -> Result<CreatePostRequest, (string * string) list>
let validateCreatePostRequest (dto : CreatePostRequestDto) =
  createPostRequest
  <!^> Latitude.tryCreate "latitude" dto.Location.Latitude
  <*^> Longitude.tryCreate "longitude" dto.Location.Longitude
  <*^> Tweet.tryCreate "tweet" dto.Tweet
```
This would be another way of creating private type with value / tryCreate without defining those functions a member in the type. Does any of this make sense? =/

**Comment by cmeeren** [comment]
It's not possible to have SRTP with module functions. But I don't see why you would need that, because there's no SRTP involved in the current definition of the operators (they simply alias `Result.bind` etc.). So AFAIK your example should work correctly already (apart from the fact that you're calling the `tryCreate` functions with two parameters, but your definition of them only accepts one parameter).

**Comment by AlbertoDePena** [comment]
@cmeeren I see your point, after looking into it a bit more, I noticed that I am not bound to using `member TryCreate` There are other ways to accomplish the same thing =)

Thanks for quick response =)

**Comment by demystifyfp** [comment]
Thanks, @cmeeren for jumping in. 

@AlbertoDePena, The rationale behind the current implementation is based on this example https://demystifyfp.gitbook.io/fstoolkit-errorhandling/index/trycreate#example-1 in the documentation. 

The overall idea was inspired by [clojure.spec](https://clojure.org/guides/spec) where each attribute type will have its own validation logic in the form a static member `TryCreate` and then compose these attributes to form different entities. By using the `Result.tryCreate`, we can leverage this individual attribute level validation across any entities.
