### ISSUE TITLE
compilation warning in Fable AsyncResult

### ISSUE THREAD

**Issue by landy** [demystifyfp/FsToolkit.ErrorHandling#92]
Hello, thank you for a great library. 

I'm not really sure if this issue should be created here, in Fable repository or it is something I did wrong. 

After I installed FsToolkit.ErrorHandling to my Safe stack project I started getting compilation error from Fable compiler:

```
WARNING in ./.fable/FsToolkit.ErrorHandling.1.4.0/AsyncResult.fs 52:13-22
"export 'awaitTask' was not found in '../fable-library.2.10.2/Async.js'
```

Any help would be appreciated

**Comment by TheAngryByrd** [comment]
Hmm “awaitTask“ shouldn’t be showing up. I might have a missed an IFDEF. I’ll investigate.

**Comment by TheAngryByrd** [comment]
Yeah looks like I need to IFDEF off https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/AsyncResult.fs#L26-L36.  What version of Fable are you running.  We have tests and they're passing so this might be a recent change to Fable.

**Comment by landy** [comment]
Im using 
fable-compiler: 2.10.2
fable-loader: 2.1.9
Fable.Core: 3.1.5

**Comment by TheAngryByrd** [comment]
Ok, give the latest 1.4.3 a try.

**Comment by landy** [comment]
It is ok now! thanks a lot for such a quick fix 👍
