### ISSUE TITLE
Async ce inside a Result ce

### ISSUE THREAD

**Issue by arunr14** [demystifyfp/FsToolkit.ErrorHandling#94]
Hello

I am using 1.4.3 
Is it possible to have an async ce inside a result ce ?  I am trying to do the following
 ```
someResult
 |> Result.bind (
    fun okValue ->
       result{
            let! (x: returnType) = async { return someAsynFunc okValue }
            return Ok (x)
       })
```
 and it gives me an error saying **No overloads match for method source**.
 I have read through issue 84 and 88 but I am still unclear on the matter. Any help is appreciated. 

Thanks

**Comment by TheAngryByrd** [comment]
No this is not possible.  `Result` CEs are for synchronous work while `AsyncResult` is for Async work.  You'll have to convert the entire chain to using `asyncResult` if you're using F#'s `Async` CE anywhere.

**Comment by arunr14** [comment]
Thank you for the clarification. Closing the issue
