### ISSUE TITLE
Latitude and Longitude mismatch in Example 2

### ISSUE THREAD

**Issue by wwinogrodzki** [demystifyfp/FsToolkit.ErrorHandling#96]
https://demystifyfp.gitbook.io/fstoolkit-errorhandling/result/map2
Of course, not relevant to the very matter that is under discussion here, but: Examples of longitude and latitude are incorrect. Longitude is -180 .. 180 and Latitude is -90 .. 90.

**Comment by TheAngryByrd** [comment]
Thanks! Can you send in a PR to fix it?

**Comment by njlr** [comment]
https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/148
